version: '3.8'

services:
  bot:
    build: .
    container_name: test-bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    container_name: test-bot-redis
    ports:
      - "6379:6379"
    restart: always
